// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC5ipoSeczuJ-uiPP9evgwJ6Ofplt2Fzg',
    appId: '1:394364552426:web:df1c84aec96e3a49d50393',
    messagingSenderId: '394364552426',
    projectId: 'movies-e7764',
    authDomain: 'movies-e7764.firebaseapp.com',
    storageBucket: 'movies-e7764.appspot.com',
    measurementId: 'G-93670NG1XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm40WfIalpv3kr8ozzF2LxKboFlTa7vcU',
    appId: '1:394364552426:android:87f524adc5be22f6d50393',
    messagingSenderId: '394364552426',
    projectId: 'movies-e7764',
    storageBucket: 'movies-e7764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr6Nj3aqZToHjyj9ZhGjufSVO-J1ZzxLI',
    appId: '1:394364552426:ios:0920215b5681ef4ad50393',
    messagingSenderId: '394364552426',
    projectId: 'movies-e7764',
    storageBucket: 'movies-e7764.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr6Nj3aqZToHjyj9ZhGjufSVO-J1ZzxLI',
    appId: '1:394364552426:ios:0920215b5681ef4ad50393',
    messagingSenderId: '394364552426',
    projectId: 'movies-e7764',
    storageBucket: 'movies-e7764.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC5ipoSeczuJ-uiPP9evgwJ6Ofplt2Fzg',
    appId: '1:394364552426:web:b1ab56c33ee57957d50393',
    messagingSenderId: '394364552426',
    projectId: 'movies-e7764',
    authDomain: 'movies-e7764.firebaseapp.com',
    storageBucket: 'movies-e7764.appspot.com',
    measurementId: 'G-0WR5MBVS03',
  );
}
